apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: environmentsdb
  namespace: default
spec:
  releaseName: environmentsdb
  targetNamespace: jira
  storageNamespace: jira
  chart:
    spec:
      chart: postgresql
      version: 13.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 60m
  values:
    global:
      postgresql:
        auth:
          database: environmentsdb
          existingSecret: jira-database-credentials
    image:
      tag: 13.3.0
    postgresqlSharedPreloadLibraries: 'pg_stat_statements'
    primary:
      initdb:
        args: '--data-checksums --lc-collate=POSIX --lc-ctype=POSIX --encoding=UTF-8'
      persistence:
        subPath: pgdata
      extendedConfiguration: |
        idle_in_transaction_session_timeout = '300s'
        shared_buffers = '256MB'
        track_activity_query_size = '2048'
        pg_stat_statements.track = 'all'
        log_min_duration_statement = '3000'
      resources:
        limits:
          cpu: 2000m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 1Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true