apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: environments
  name: environments
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: environments
  type: NodePort
status:
  loadBalancer: {}