apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: index-docker-io-v1
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBKezK55yXatxulyQa11VcVu7Btw/0AAZA+rHMnt6YFX0oR9uIMB0dYKsiMeKe071xMTmE4S7ud+9KobaQdFmr6Nq6nstWgWZAKK7IKqVBOMpIMvzAdCrYk4p5a/N+jQmR2kQkDCflMxExRgZUoHl2OiRlWczDw9KvrE8QDvt0UEVeZA1HDFUfUDVFALaaTJtyPs8ozvBWUfI2LrJIX6zM7WxgMWwdGZgnru90/Do4XD7BUfFu/7Rx2U/DRgHskxJv2onTUhq+LD8Wu8nf3dckc1jn8CF3wTuiqdA/SoOunPpvVsYhLY8+L6nH7aCo1EJZbxFY2sM+g7TK09NulEHgG6tYmkIdan0ew75FBh0BqzMjt33VTxAIbDsnNbImOzPBcZQ7cP+aS9uixFgxpaHVI0RlCDI6QtiOYYQWW33dJHeZAmd67oCd7yKtZ8UXivLF7C33yVsdGnxnhWVdeLF76B9bCd9ZsoUJu6wQKJs6rDo2JLoISAl3UeXjXBhKpq1ns71dgaZxe7+sHBLrEkrh25uh4yIyiHorVmnTj2WfZ2hXnoTgqq0xhEr7POfzwMTZWFFhUx2stuO69VPEzKsN1OXCFNBTI56SDWwjOKIZtk4fdPthRNS2QFVD2UiBY0Zdrtai47SKbPuFKZTrELAkcdZ6zjrxgOt6jmL98ICKnhAg+E8KIuLZ+iRJIdKUwkSCSmUiVOkxqRfJMibNvdemgTJl/puwQuG6XbcPWxdoMWIpib30mFQ9MiggNcKb/LemQez6ORK7ydKOYCckmx19yQbNOxR2fSyKzKLymnHJNphUrsOcfDXhV9W1FKMdbNpWdun63atPaENth5n2K0ZjLvE1JOIML+7FT4tKZZTKduY+ZvLNKWw1oAkfZtTRuiw==
  template:
    metadata:
      creationTimestamp: null
      name: index-docker-io-v1
      namespace: default
    type: kubernetes.io/dockerconfigjson
